// 异步请求需要定义成数组，非异步直接定义为常量字符串即可
// project
export const GET_PROJECTS = ['GET_PROJECTS_REQUEST', 'GET_PROJECTS_SUCCESS', 'GET_PROJECTS_FAILURE'];
export const GET_PROJECTLIST = ['GET_PROJECTLIST_REQUEST', 'GET_PROJECTLIST_SUCCESS', 'GET_PROJECTLIST_FAILURE'];
export const SET_LOGLEVEL = ['SET_LOGLEVEL_REQUEST', 'SET_LOGLEVEL_SUCCESS', 'SET_LOGLEVEL_FAILURE'];
export const UPDATE_PROJECT = ['UPDATE_PROJECT_REQUEST', 'UPDATE_PROJECT_SUCCESS', 'UPDATE_PROJECT_FAILURE'];
export const INSERT_PROJECT = ['INSERT_PROJECT_REQUEST', 'INSERT_PROJECT_SUCCESS', 'INSERT_PROJECT_FAILURE'];
export const SORT_PROJECTLIST = 'SORT_PROJECTLIST';
export const SET_MOCK = ['SET_MOCK_REQUEST', 'SET_MOCK_SUCCESS', 'SET_MOCK_FAILURE'];
export const LASTPROEJCT = 'LASTPROEJCT';
// case
export const RUNCASE = ['RUNCASE_REQUEST', 'RUNCASE_SUCCESS', 'RUNCASE_FAILURE'];
export const GET_ALLCASES = ['GET_ALLCASES_REQUEST', 'GET_ALLCASES_SUCCESS', 'GET_ALLCASES_FAILURE'];
export const GET_CASELIST = ['GET_CASELIST_REQUEST', 'GET_CASELIST_SUCCESS', 'GET_CASELIST_FAILURE'];
export const GET_CASE_APILIST = ['GET_CASE_APILIST_REQUEST', 'GET_CASE_APILIST_SUCCESS', 'GET_CASE_APILIST_FAILURE'];
export const INSERT_CASEINFO = ['INSERT_CASEINFO_REQUEST', 'INSERT_CASEINFO_SUCCESS', 'INSERT_CASEINFO_FAILURE'];
export const DELETE_CASEINFO = ['DELETE_CASEINFO_REQUEST', 'DELETE_CASEINFO_SUCCESS', 'DELETE_CASEINFO_FAILURE'];
export const UPDATE_CASEINFO = ['UPDATE_CASEINFO_REQUEST', 'UPDATE_CASEINFO_SUCCESS', 'UPDATE_CASEINFO_FAILURE'];
export const REPLACE_CASEINFO = ['REPLACE_CASEINFO_REQUEST', 'REPLACE_CASEINFO_SUCCESS', 'REPLACE_CASEINFO_FAILURE'];
export const COPY_CASEINFO = ['COPY_CASEINFO_REQUEST', 'COPY_CASEINFO_SUCCESS', 'COPY_CASEINFO_FAILURE'];
export const ADD_CASE = ['ADD_CASE_REQUEST', 'ADD_CASE_SUCCESS', 'ADD_CASE_FAILURE'];
export const DELETE_CASE = ['ADD_CASE_REQUEST', 'ADD_CASE_SUCCESS', 'ADD_CASE_FAILURE'];
export const GET_CASE = ['ADD_CASE_REQUEST', 'ADD_CASE_SUCCESS', 'ADD_CASE_FAILURE'];
export const DEBUG_CASE = ['ADD_CASE_REQUEST', 'ADD_CASE_SUCCESS', 'ADD_CASE_FAILURE'];
export const COPY_CASE = ['COPY_CASE_REQUEST', 'COPY_CASE_SUCCESS', 'COPY_CASE_FAILURE'];
export const MOVE_CASE = ['MOVE_CASE_REQUEST', 'MOVE_CASE_SUCCESS', 'MOVE_CASE_FAILURE'];
export const GET_GLOBAL = ['GET_GLOBAL_REQUEST', 'GET_GLOBAL_SUCCESS', 'GET_GLOBAL_FAILURE'];
export const GETFAILEDCATEGORY = ['GETFAILEDCATEGORY_REQUEST', 'GETFAILEDCATEGORY_SUCCESS', 'GETFAILEDCATEGORY_FAILURE'];
export const GETFAILEDLIST = ['GETFAILEDLIST_REQUEST', 'GETFAILEDLIST_SUCCESS', 'GETFAILEDLIST_FAILURE'];
export const SAVEFAILEDDETAIL = ['SAVEFAILEDDETAIL_REQUEST', 'SAVEFAILEDDETAIL_SUCCESS', 'SAVEFAILEDDETAIL_FAILURE'];
// floder
export const GET_FOLDERLIST = ['GET_FOLDERLIST_REQUEST', 'GET_FOLDERLIST_SUCCESS', 'GET_FOLDERLIST_FAILURE'];
export const GET_ALLFOLDERS = ['GET_ALLFOLDERS_REQUEST', 'GET_ALLFOLDERS_SUCCESS', 'GET_ALLFOLDERS_FAILURE'];
export const ADD_FOLDER = ['ADD_FOLDER_REQUEST', 'ADD_FOLDER_SUCCESS', 'ADD_FOLDER_FAILURE'];
export const UPDATE_FOLDER = ['UPDATE_FOLDER_REQUEST', 'UPDATE_FOLDER_SUCCESS', 'UPDATE_FOLDER_FAILURE'];
export const ADD_FOLDER_VIRTUAL = 'ADD_FOLDER_VIRTUAL';
export const SHOW_NEWFOLDER = 'SHOW_NEWFOLDER';
export const COPY_FOLDER = ['COPY_FOLDER_REQUEST', 'COPY_FOLDER_SUCCESS', 'COPY_FOLDER_FAILURE'];
export const DELETE_FOLDER = ['DELETE_FOLDER_REQUEST', 'DELETE_FOLDER_SUCCESS', 'DELETE_FOLDER_FAILURE'];
// api
export const GET_APILIST = ['GET_APILIST_REQUEST', 'GET_APILIST_SUCCESS', 'GET_APILIST_FAILURE'];
export const GET_RESPONSESBODIES = ['GET_RESPONSESBODIES_REQUEST', 'GET_RESPONSESBODIES_SUCCESS', 'GET_RESPONSESBODIES_FAILURE'];
// database
export const TESTCONNECTION = ['TESTCONNECTION_REQUEST', 'TESTCONNECTION_SUCCESS', 'TESTCONNECTION_FAILURE'];
export const SAVEDBCONFIG = ['SAVEDBCONFIG_REQUEST', 'SAVEDBCONFIG_SUCCESS', 'SAVEDBCONFIG_FAILURE'];
export const TESTSUCCESS = 'TESTSUCCESS';
export const GETCONFIGDATA = ['GETCONFIGDATA_REQUEST', 'GETCONFIGDATA_SUCCESS', 'GETCONFIGDATA_FAILURE'];
export const GETALLALIAS = ['GETALLALIAS_REQUEST', 'GETALLALIAS_SUCCESS', 'GETALLALIAS_FAILURE'];
export const GETDBLIST = ['GETDBLIST_REQUEST', 'GETDBLIST_SUCCESS', 'GETDBLIST_FAILURE'];
export const DELETEDBCONFIG = ['DELETEDBCONFIG_REQUEST', 'DELETEDBCONFIG_SUCCESS', 'DELETEDBCONFIG_FAILURE'];
// commonConfig
export const GETALLEVN = ['GETALLEVN_REQUEST', 'GETALLEVN_SUCCESS', 'GETALLEVN_FAILURE'];
export const UPDATECONFIG = ['UPDATECONFIG_REQUEST', 'UPDATECONFIG_SUCCESS', 'UPDATECONFIG_FAILURE'];
export const GETCONFIGLIST = ['GETCONFIGLIST_REQUEST', 'GETCONFIGLIST_SUCCESS', 'GETCONFIGLIST_FAILURE'];
export const GETPROJECTENTRIES = ['GETPROJECTENTRIES_REQUEST', 'GETPROJECTENTRIES_SUCCESS', 'GETPROJECTENTRIES_FAILURE'];
export const GETAPPIDS = ['GETAPPIDS_REQUEST', 'GETAPPIDS_SUCCESS', 'GETAPPIDS_FAILURE'];
export const GETIFACES = ['GETIFACES_REQUEST', 'GETIFACES_SUCCESS', 'GETIFACES_FAILURE'];
export const GETMETHODLIST = ['GETMETHODLIST_REQUEST', 'GETMETHODLIST_SUCCESS', 'GETMETHODLIST_FAILURE'];
export const GETLOGLIST = ['GETLOGLIST_REQUEST', 'GETLOGLIST_SUCCESS', 'GETLOGLIST_FAILURE'];
export const GETLOGITEMDETAIL = ['GETLOGITEMDETAIL_REQUEST', 'GETLOGITEMDETAIL_SUCCESS', 'GETLOGITEMDETAIL_FAILURE'];
export const UPLOADHAR = ['UPLOADHAR_REQUEST', 'UPLOADHAR_SUCCESS', 'UPLOADHAR_FAILURE'];
export const SAVEHAR = ['SAVEHAR_REQUEST', 'SAVEHAR_SUCCESS', 'SAVEHAR_FAILURE'];
export const GETSERVICES = ['GETSERVICES_REQUEST', 'GETSERVICES_SUCCESS', 'GETSERVICES_FAILURE'];
export const RESETAPPIDS = 'RESETAPPIDS';
export const RESETIFACES = 'RESETIFACES';
export const RESETSERVICES = 'RESETSERVICES';
export const SETAPP = 'SETAPP';
export const SETIFACE = 'SETIFACE';
export const SETMETHODLIST = 'SETMETHODLIST';
export const SETLOGLIST = 'SETLOGLIST';
export const SETTIMEQUANTUM = 'SETTIMEQUANTUM';
export const SETPATHIDS = 'SETPATHIDS';
export const SETPROJECT = 'SETPROJECT';
export const DELETEMETHODITEM = 'DELETEMETHODITEM';
export const GET_PROJECT_COVERAGE = ['GET_PROJECT_COVERAGE_REQUEST', 'GET_PROJECT_COVERAGE_SUCCESS', 'GET_PROJECT_COVERAGE_FAILURE'];
export const UPLOADMOCK = ['UPLOADMOCK_REQUEST', 'UPLOADMOCK_SUCCESS', 'UPLOADMOCK_FAILURE'];
export const UPLOADHARTOJMX = ['UPLOADHARTOJMX_REQUEST', 'UPLOADHARTOJMX_SUCCESS', 'UPLOADHARTOJMX_FAILURE'];
export const SAVEUNITCASE = ['SAVEUNITCASE_REQUEST', 'SAVEUNITCASE_SUCCESS', 'SAVEUNITCASE_FAILURE'];
